In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("powerplant_data.csv")

In [3]:
df.head()

      AT      V       AP     RH      PE
0   8.34  40.77  1010.84  90.01  480.48
1  23.64  58.49  1011.40  74.20  445.75
2  29.74  56.90  1007.15  41.91  438.76
3  19.07  49.69  1007.22  76.79  453.09
4  11.80  40.66  1017.13  97.20  464.43

In [4]:
df.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [5]:
X = df.drop("PE", axis = 1)
Y = df["PE"]

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size = 0.3, random_state = 42
)

In [7]:
df.shape

(9568, 5)

In [8]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [9]:
X_test_scaled

array([[ 1.35027377,  0.23835089, -1.2868797 , -1.1152662 ],
       [ 0.81612819,  1.36219539, -0.74354734,  0.25518223],
       [-0.23877586, -0.73921294,  1.9883008 , -0.20689783],
       ...,
       [ 0.23512774,  0.27059555,  0.93538342, -0.23848131],
       [-1.79971257, -1.42106962,  2.6025026 ,  1.16698358],
       [ 1.16285427,  0.78729663, -0.34195385, -0.32361939]])

In [10]:
type(X_train_scaled)

numpy.ndarray

In [11]:
type(Y_train)

pandas.Series

In [12]:
print(X_train_scaled.shape)

(6697, 4)

In [13]:
print(Y_train.shape)

(6697,)

In [14]:
import torch
import torch.nn as nn

X_train_tensor = torch.tensor(X_train_scaled, dtype = torch.float32)
X_test_tensor = torch.tensor(X_test_scaled, dtype = torch.float32)

Y_train_tensor = torch.tensor(Y_train.values, dtype = torch.float32).view(-1, 1)
Y_test_tensor = torch.tensor(Y_test.values, dtype = torch.float32).view(-1, 1)

In [15]:
#the datatype above X_train_scaled is float, hence dtype is float32

#upar datatype of X_train_scaled is numpy array, issliee we can access it directly
#but Y_train ka is pandas series, so to access values we use .values

#the shape of X_train_scaled is (n, m), but that of Y_train is (n)
#so to convert it from 1 array to the required format, we used .views(-1, 1)

In [16]:
#Dataloader is used to define how data will be loaded for training
#TensorDataset is used to define data. it combines multiples tensors into single datasheet

In [17]:
from torch.utils.data import TensorDataset, DataLoader

train_dataset = TensorDataset(X_train_tensor, Y_train_tensor)
test_dataset = TensorDataset(X_test_tensor,  Y_test_tensor)

In [18]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size = 32)

DEEP LEARNING

In [19]:
#Define an ANN model

class ANN(nn.Module):
    def __init__(self):
        super(ANN, self).__init__()

        self.model = nn.Sequential(
            #1st hidden layer
            #nn.Linear(input_features, output_features)
            nn.Linear(X_train.shape[1], 6),
            nn.ReLU(),

            #2nd hidden layer
            nn.Linear(6, 6),
            nn.ReLU(),

            #output layer
            nn.Linear(6, 1),
        )


    def forward(self, x):
        return self.model(x)

In [20]:
import torch.optim as optim

model = ANN()

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters())

In [21]:
#Training
epochs = 100
train_losses = []
val_losses = []

best_val_loss = float("inf")

for epoch in range (epochs):
    model.train()
    running_loss = 0.0

    for xb, yb in train_loader:
        # xb = features of 1 batch
        # yb = labels of 1 batch
        optimizer.zero_grad()   #it is used to adjust the gradients

        outputs = model(xb)     #forwards propagation 
        loss = criterion(outputs, yb)    # use to calculate loss between current trained batch and already existing labels of that batch.
        loss.backward()        #backward propagation ... compute gradients
        optimizer.step()       #params update

        running_loss += loss.item()   #to convert pytorch tensor value to python, we use .items()

        epoch_train_loss = running_loss / len(train_loader)
        train_losses.append(epoch_train_loss)

    #Validation
    #validation mai we don't do backward prop as no weight readjustment etc is needed.
    model.eval()          #we need to add this statement to show that we have started evaluation
    running_val_loss = 0.0

    #by default pytorch mai auto grad hota hai jisme it automatically calculates gradient, so yaha gradient calculte na karneko kaha gya hai (no backward propagation)
    with torch.no_grad():  
        for xb, yb in test_loader:
            outputs = model(xb)
            loss = criterion(outputs, yb)
            running_val_loss += loss.item()

    epoch_val_loss = running_val_loss / len(test_loader)
    val_losses.append(epoch_val_loss)

    print(f"epoch {epoch+1}/{epochs} ==> train loss = {epoch_train_loss} & val loss = {epoch_val_loss}")

    if epoch_val_loss < best_val_loss:
        best_val_loss = epoch_val_loss
        torch.save(model.state_dict(), "best_model.pt")

epoch 1/100 ==> train loss = 205893.61473214286 & val loss = 203534.91770833332
epoch 2/100 ==> train loss = 196166.03117559524 & val loss = 183740.91302083334
epoch 3/100 ==> train loss = 163673.23199404762 & val loss = 138759.82274305556
epoch 4/100 ==> train loss = 114956.28240327381 & val loss = 90561.46675347222
epoch 5/100 ==> train loss = 73617.4515811012 & val loss = 56543.108723958336
epoch 6/100 ==> train loss = 44378.745796130956 & val loss = 32110.116319444445
epoch 7/100 ==> train loss = 23889.765973772322 & val loss = 16483.256184895832
epoch 8/100 ==> train loss = 12504.852822730654 & val loss = 9207.351302083332
epoch 9/100 ==> train loss = 7753.268645368304 & val loss = 6260.126814778646
epoch 10/100 ==> train loss = 5558.191500418527 & val loss = 4648.106431749132
epoch 11/100 ==> train loss = 4209.872798084078 & val loss = 3536.5957478841146
epoch 12/100 ==> train loss = 3213.4036493210565 & val loss = 2692.90638156467
epoch 13/100 ==> train loss = 2462.635746837798 & val loss = 2076.0491231282554
epoch 14/100 ==> train loss = 1925.9137340727307 & val loss = 1645.002062310113
epoch 15/100 ==> train loss = 1543.3037030901228 & val loss = 1340.9724161783854
epoch 16/100 ==> train loss = 1280.4976298014324 & val loss = 1125.2825642903647
epoch 17/100 ==> train loss = 1080.2979730515253 & val loss = 956.1469004313151
epoch 18/100 ==> train loss = 925.2280067080543 & val loss = 818.5221306694879
epoch 19/100 ==> train loss = 795.6165748232887 & val loss = 705.6085405137803
epoch 20/100 ==> train loss = 684.8642540341332 & val loss = 606.0732269287109
epoch 21/100 ==> train loss = 589.6745420910063 & val loss = 519.9360134548612
epoch 22/100 ==> train loss = 504.8395184471494 & val loss = 441.6848154703776
epoch 23/100 ==> train loss = 426.7374943324498 & val loss = 372.26684027777776
epoch 24/100 ==> train loss = 359.3987882704962 & val loss = 313.4505633884006
epoch 25/100 ==> train loss = 300.1956915355864 & val loss = 260.7659780714247
epoch 26/100 ==> train loss = 248.4351443699428 & val loss = 215.14789174397785
epoch 27/100 ==> train loss = 204.60446446736654 & val loss = 174.67873441908094
epoch 28/100 ==> train loss = 164.7696538289388 & val loss = 141.5916367848714
epoch 29/100 ==> train loss = 131.70710191272553 & val loss = 112.33166842990451
epoch 30/100 ==> train loss = 104.41591117495582 & val loss = 88.54667922125923
epoch 31/100 ==> train loss = 81.75137661525181 & val loss = 71.50774476793077
epoch 32/100 ==> train loss = 65.27590522766113 & val loss = 56.722490035163034
epoch 33/100 ==> train loss = 52.316021392458964 & val loss = 46.67097837660048
epoch 34/100 ==> train loss = 43.35137292316982 & val loss = 38.31697991689046
epoch 35/100 ==> train loss = 36.48097147260393 & val loss = 33.13115118874444
epoch 36/100 ==> train loss = 31.85086638132731 & val loss = 29.424910513559976
epoch 37/100 ==> train loss = 28.870602321624755 & val loss = 27.484909428490532
epoch 38/100 ==> train loss = 27.276517491113573 & val loss = 25.483036189609102
epoch 39/100 ==> train loss = 25.379354567754838 & val loss = 24.0725598971049
epoch 40/100 ==> train loss = 24.39921116601853 & val loss = 23.18344022962782
epoch 41/100 ==> train loss = 23.730809538705007 & val loss = 22.604211886723835
epoch 42/100 ==> train loss = 23.134385876428514 & val loss = 21.87671159638299
epoch 43/100 ==> train loss = 22.809591484069824 & val loss = 21.519785181681314
epoch 44/100 ==> train loss = 22.474653484707787 & val loss = 21.275729571448434
epoch 45/100 ==> train loss = 22.28100242614746 & val loss = 21.1647835360633
epoch 46/100 ==> train loss = 22.034422265915644 & val loss = 20.704853826098972
epoch 47/100 ==> train loss = 21.766220773969376 & val loss = 20.509000047047934
epoch 48/100 ==> train loss = 21.683326185317267 & val loss = 20.270537016126845
epoch 49/100 ==> train loss = 21.543364978971937 & val loss = 20.324844370947943
epoch 50/100 ==> train loss = 21.577668553306943 & val loss = 20.006841140323214
epoch 51/100 ==> train loss = 21.454346929277694 & val loss = 20.14748853047689
epoch 52/100 ==> train loss = 21.55519321305411 & val loss = 20.02448796696133
epoch 53/100 ==> train loss = 21.365281790778752 & val loss = 20.528353532155354
epoch 54/100 ==> train loss = 21.34543601217724 & val loss = 19.778042634328205
epoch 55/100 ==> train loss = 21.418833578200566 & val loss = 20.050493897332085
epoch 56/100 ==> train loss = 21.246019699459985 & val loss = 20.163239606221516
epoch 57/100 ==> train loss = 21.236937218620664 & val loss = 19.68288780318366
epoch 58/100 ==> train loss = 21.207590884254092 & val loss = 19.840759388605754
epoch 59/100 ==> train loss = 21.306157130286806 & val loss = 19.833581437004938
epoch 60/100 ==> train loss = 21.16847407023112 & val loss = 19.793201160430907
epoch 61/100 ==> train loss = 21.107359373001824 & val loss = 19.96547549035814
epoch 62/100 ==> train loss = 21.263504123687746 & val loss = 19.78145497639974
epoch 63/100 ==> train loss = 21.204369808378672 & val loss = 19.560099098417496
epoch 64/100 ==> train loss = 20.992792597271148 & val loss = 20.151908599005804
epoch 65/100 ==> train loss = 21.160376253582182 & val loss = 19.852809715270997
epoch 66/100 ==> train loss = 21.091934254055932 & val loss = 20.068454509311252
epoch 67/100 ==> train loss = 21.049296769641696 & val loss = 20.224298583136665
epoch 68/100 ==> train loss = 21.155474358513242 & val loss = 19.548792674806382
epoch 69/100 ==> train loss = 21.066398257300968 & val loss = 19.743559233347575
epoch 70/100 ==> train loss = 21.177519180661157 & val loss = 19.51998363600837
epoch 71/100 ==> train loss = 21.073165963944934 & val loss = 20.300182798173694
epoch 72/100 ==> train loss = 21.06410507474627 & val loss = 20.530300437079536
epoch 73/100 ==> train loss = 21.048106336593627 & val loss = 19.366896041234334
epoch 74/100 ==> train loss = 21.066961111341204 & val loss = 19.71786757045322
epoch 75/100 ==> train loss = 21.080117965879893 & val loss = 19.387612544165716
epoch 76/100 ==> train loss = 21.060293174925306 & val loss = 19.702562840779624
epoch 77/100 ==> train loss = 21.158303310757592 & val loss = 19.684460173712836
epoch 78/100 ==> train loss = 20.92936682928176 & val loss = 19.807033835517036
epoch 79/100 ==> train loss = 20.911852777571905 & val loss = 20.483473184373644
epoch 80/100 ==> train loss = 21.001277778262185 & val loss = 19.34632486767239
epoch 81/100 ==> train loss = 20.821259607587542 & val loss = 19.912054332097373
epoch 82/100 ==> train loss = 20.89429573785691 & val loss = 19.435440752241348
epoch 83/100 ==> train loss = 20.88083036059425 & val loss = 19.25689146783617
epoch 84/100 ==> train loss = 20.77064839771816 & val loss = 20.33443800608317
epoch 85/100 ==> train loss = 20.923490860348657 & val loss = 19.635607973734537
epoch 86/100 ==> train loss = 21.02854350862049 & val loss = 19.232928392622206
epoch 87/100 ==> train loss = 20.919084053947813 & val loss = 19.72124483320448
epoch 88/100 ==> train loss = 20.832479413350423 & val loss = 20.08612256579929
epoch 89/100 ==> train loss = 20.882122825440906 & val loss = 19.238153404659695
epoch 90/100 ==> train loss = 20.983687686920167 & val loss = 19.626783190833198
epoch 91/100 ==> train loss = 20.858387170519148 & val loss = 19.421152867211237
epoch 92/100 ==> train loss = 20.954352001916796 & val loss = 19.285124333699546
epoch 93/100 ==> train loss = 20.818873786926268 & val loss = 19.273749155468412
epoch 94/100 ==> train loss = 20.98941162654332 & val loss = 19.272515116797553
epoch 95/100 ==> train loss = 20.912573396591913 & val loss = 19.504996713002523
epoch 96/100 ==> train loss = 20.849240184965588 & val loss = 19.37495429780748
epoch 97/100 ==> train loss = 20.771845590500604 & val loss = 19.551352998945447
epoch 98/100 ==> train loss = 20.857685563677833 & val loss = 19.55053735309177
epoch 99/100 ==> train loss = 20.815436558496383 & val loss = 19.192534414927163
epoch 100/100 ==> train loss = 20.678008683522542 & val loss = 19.864348443349204

In [22]:
import matplotlib.pyplot as plt

loss_df = pd.DataFrame({
    "Training Loss": train_losses,
    "Validation Loss": val_losses
})

plt.plot(loss_df["Training Loss"], label = "Training Loss")
plt.plot(loss_df["Validation Loss"], label = "Validation Loss")

plt.xlabel("Epochs")
plt.ylabel("Losses")

plt.legend()

ValueError: All arrays must be of the same length

In [23]:
#When we are judging our model performance we must do it based on model's validatiom loss. becoz it shows unknown data pe kaisa performance hai.
model.load_state_dict(torch.load("best_model.pt"))

#best model . pt se hum sare weights k values lete hai, torch.load se we get the raw values and then , we load it to the model using load_state

In [24]:
#Evaluation

model.eval()
with torch.no_grad():
    train_preds = model(X_train_tensor)
    test_preds = model(X_test_tensor)

    train_mse_loss = criterion(train_preds, Y_train_tensor)
    test_mse_loss = criterion(test_preds, Y_test_tensor)

print("Training MSE: ", train_mse_loss.item())
print("Testing MSE: ", test_mse_loss.item())

Training MSE:  20.480268478393555
Testing MSE:  19.17917251586914

In [25]:
from sklearn.metrics import r2_score

print("r2 score =", r2_score(Y_test, test_preds))

r2 score = 0.9333980244640051

In [28]:
predicted_df = pd.DataFrame(test_preds.numpy(),  columns = ["Predicted Values"])
actual_df = pd.DataFrame(Y_test.values,  columns = ["Actual Values"])

pd.concat([predicted_df, actual_df], axis = 1)

      Predicted Values  Actual Values
0           435.189178         433.27
1           436.780212         438.16
2           461.547302         458.42
3           476.682800         480.82
4           435.035461         441.41
...                ...            ...
2866        480.545776         480.31
2867        452.774567         446.77
2868        450.761719         454.66
2869        484.230042         483.77
2870        434.996033         441.51

[2871 rows x 2 columns]

In [1]:
type(test_preds)

NameError: name 'test_preds' is not defined